<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

/**
 * Seed reference data for property types, ownership statuses,
 * ownership types, and document types.
 *
 * Data sourced from WISEBOX-PROJECT-BIBLE.md.
 */
return new class extends Migration
{
    public function up(): void
    {
        $now = now();

        // Property Types (3)
        DB::table('property_types')->insertOrIgnore([
            [
                'name' => 'Land',
                'slug' => 'land',
                'description' => 'Includes ground, structure and water',
                'icon' => 'land',
                'is_active' => true,
                'sort_order' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Apartment',
                'slug' => 'apartment',
                'description' => 'Residential unit in a building complex',
                'icon' => 'apartment',
                'is_active' => true,
                'sort_order' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Others',
                'slug' => 'others',
                'description' => 'Any other type',
                'icon' => 'building',
                'is_active' => true,
                'sort_order' => 3,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);

        // Ownership Statuses (7)
        DB::table('ownership_statuses')->insertOrIgnore([
            [
                'name' => 'Ownership by Purchase / Sale Deed',
                'slug' => 'purchase',
                'display_label' => 'I purchased it',
                'bengali_label' => 'কয়',
                'description' => 'This property is exclusively yours',
                'is_active' => true,
                'sort_order' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Ownership by Gift (Heba / Gift Deed)',
                'slug' => 'gift',
                'display_label' => 'I received it as a gift',
                'bengali_label' => 'হেবা',
                'description' => 'Ownership can be claimed by multiple entity',
                'is_active' => true,
                'sort_order' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Ownership by Inheritance / Succession',
                'slug' => 'inheritance',
                'display_label' => 'I inherited it',
                'bengali_label' => 'উত্তরাধিকার',
                'description' => 'Property received through inheritance or succession',
                'is_active' => true,
                'sort_order' => 3,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Ownership by Court Decree / Order',
                'slug' => 'court-decree',
                'display_label' => 'I own it by court order/decree',
                'bengali_label' => 'ডিক্রি',
                'description' => 'Ownership established through court decree or order',
                'is_active' => true,
                'sort_order' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Ownership by Settlement / Lease / Patta',
                'slug' => 'lease',
                'display_label' => 'I own it by lease',
                'bengali_label' => 'বন্দোবস্ত',
                'description' => 'Ownership through settlement, lease, or patta',
                'is_active' => true,
                'sort_order' => 5,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Ownership by Donation / Religious Trust (Devottor / Waqf)',
                'slug' => 'donation-trust',
                'display_label' => 'I own it by donation or trust',
                'bengali_label' => 'এওয়াজ/বিনিময়',
                'description' => 'Ownership through donation or religious trust',
                'is_active' => true,
                'sort_order' => 6,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Family Property (Registered in Parents Name)',
                'slug' => 'family',
                'display_label' => 'It is family property',
                'bengali_label' => 'পারিবারিক সম্পত্তি',
                'description' => 'Property registered in parents or family name',
                'is_active' => true,
                'sort_order' => 7,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);

        // Ownership Types (2)
        DB::table('ownership_types')->insertOrIgnore([
            [
                'name' => 'Sole Owner',
                'slug' => 'sole',
                'description' => 'You are the only owner of this property',
                'requires_co_owners' => false,
                'is_active' => true,
                'sort_order' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Joint Ownership',
                'slug' => 'joint',
                'description' => 'This property has multiple co-owners',
                'requires_co_owners' => true,
                'is_active' => true,
                'sort_order' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);

        // Document Types: Primary (4)
        DB::table('document_types')->insertOrIgnore([
            [
                'name' => 'Deed (Dolil)',
                'slug' => 'deed',
                'description' => 'The primary legal document proving ownership',
                'category' => 'primary',
                'is_required' => true,
                'guidance_text' => 'Upload your original deed document or a certified copy.',
                'missing_guidance' => 'Contact your local sub-registry office to obtain a copy of your deed.',
                'accepted_formats' => json_encode(['pdf', 'jpg', 'jpeg', 'png']),
                'max_file_size_mb' => 10,
                'score_weight' => 30,
                'conditional_on_ownership' => null,
                'is_active' => true,
                'sort_order' => 1,
                'country_code' => 'BGD',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'LD Tax / Dakhila / Rent Receipt (Khazna)',
                'slug' => 'tax-receipt',
                'description' => 'Land development tax or rent receipt',
                'category' => 'primary',
                'is_required' => true,
                'guidance_text' => 'Upload your most recent land tax payment receipt.',
                'missing_guidance' => 'Visit your local Union Parishad or Pourashava to obtain a tax receipt.',
                'accepted_formats' => json_encode(['pdf', 'jpg', 'jpeg', 'png']),
                'max_file_size_mb' => 10,
                'score_weight' => 25,
                'conditional_on_ownership' => null,
                'is_active' => true,
                'sort_order' => 2,
                'country_code' => 'BGD',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Mutation Khatian',
                'slug' => 'mutation-khatian',
                'description' => 'Registered legal agreement for property transfer records',
                'category' => 'primary',
                'is_required' => true,
                'guidance_text' => 'Upload your mutation khatian (namjari) document.',
                'missing_guidance' => 'Apply for mutation at your local AC Land office.',
                'accepted_formats' => json_encode(['pdf', 'jpg', 'jpeg', 'png']),
                'max_file_size_mb' => 10,
                'score_weight' => 25,
                'conditional_on_ownership' => null,
                'is_active' => true,
                'sort_order' => 3,
                'country_code' => 'BGD',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Recorded Khatian (RS/BS/CS/BRS/BDS)',
                'slug' => 'recorded-khatian',
                'description' => 'Official government land record (Record of Rights)',
                'category' => 'primary',
                'is_required' => false,
                'guidance_text' => 'Upload your recorded khatian from any survey (RS, BS, CS, BRS, or BDS).',
                'missing_guidance' => 'Obtain a certified copy from the District Record Room or AC Land office.',
                'accepted_formats' => json_encode(['pdf', 'jpg', 'jpeg', 'png']),
                'max_file_size_mb' => 10,
                'score_weight' => 20,
                'conditional_on_ownership' => null,
                'is_active' => true,
                'sort_order' => 4,
                'country_code' => 'BGD',
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);

        // Document Types: Secondary (7)
        DB::table('document_types')->insertOrIgnore([
            [
                'name' => 'Court Order / Decree',
                'slug' => 'court-decree',
                'description' => 'Court order or decree establishing ownership',
                'category' => 'secondary',
                'is_required' => false,
                'guidance_text' => 'Upload the court order or decree document.',
                'missing_guidance' => 'Contact your lawyer or the issuing court for a certified copy.',
                'accepted_formats' => json_encode(['pdf', 'jpg', 'jpeg', 'png']),
                'max_file_size_mb' => 10,
                'score_weight' => 10,
                'conditional_on_ownership' => 'court-decree',
                'is_active' => true,
                'sort_order' => 5,
                'country_code' => 'BGD',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Duplicate Carbon Receipt (DCR)',
                'slug' => 'dcr',
                'description' => 'Official duplicate of a lost land registration receipt',
                'category' => 'secondary',
                'is_required' => false,
                'guidance_text' => 'Upload your Duplicate Carbon Receipt.',
                'missing_guidance' => 'Apply at the sub-registry office where the deed was originally registered.',
                'accepted_formats' => json_encode(['pdf', 'jpg', 'jpeg', 'png']),
                'max_file_size_mb' => 10,
                'score_weight' => 5,
                'conditional_on_ownership' => null,
                'is_active' => true,
                'sort_order' => 6,
                'country_code' => 'BGD',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Position of the Land',
                'slug' => 'position-of-land',
                'description' => 'Document showing exact physical location and boundaries',
                'category' => 'secondary',
                'is_required' => false,
                'guidance_text' => 'Upload a document or map showing the land position.',
                'missing_guidance' => 'Contact a licensed surveyor to prepare a position document.',
                'accepted_formats' => json_encode(['pdf', 'jpg', 'jpeg', 'png']),
                'max_file_size_mb' => 10,
                'score_weight' => 5,
                'conditional_on_ownership' => null,
                'is_active' => true,
                'sort_order' => 7,
                'country_code' => 'BGD',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Possession of the Land',
                'slug' => 'possession-of-land',
                'description' => 'Document proving actual physical control and use',
                'category' => 'secondary',
                'is_required' => false,
                'guidance_text' => 'Upload proof of possession (utility bills, tax receipts, etc.).',
                'missing_guidance' => 'Gather utility bills, tax receipts, or witness statements as proof.',
                'accepted_formats' => json_encode(['pdf', 'jpg', 'jpeg', 'png']),
                'max_file_size_mb' => 10,
                'score_weight' => 5,
                'conditional_on_ownership' => null,
                'is_active' => true,
                'sort_order' => 8,
                'country_code' => 'BGD',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Settlement / Lease Gazettes',
                'slug' => 'settlement-gazette',
                'description' => 'Official government notifications granting land',
                'category' => 'secondary',
                'is_required' => false,
                'guidance_text' => 'Upload settlement or lease gazette documents.',
                'missing_guidance' => 'Check with the DC office or gazette publication records.',
                'accepted_formats' => json_encode(['pdf', 'jpg', 'jpeg', 'png']),
                'max_file_size_mb' => 10,
                'score_weight' => 5,
                'conditional_on_ownership' => 'lease',
                'is_active' => true,
                'sort_order' => 9,
                'country_code' => 'BGD',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Succession Certificate',
                'slug' => 'succession-certificate',
                'description' => 'Certificate establishing succession rights',
                'category' => 'secondary',
                'is_required' => false,
                'guidance_text' => 'Upload your succession certificate or related documents.',
                'missing_guidance' => 'Apply for a succession certificate through the local court.',
                'accepted_formats' => json_encode(['pdf', 'jpg', 'jpeg', 'png']),
                'max_file_size_mb' => 10,
                'score_weight' => 10,
                'conditional_on_ownership' => 'inheritance',
                'is_active' => true,
                'sort_order' => 10,
                'country_code' => 'BGD',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Via Deed',
                'slug' => 'via-deed',
                'description' => 'Historical deed showing chain of ownership',
                'category' => 'secondary',
                'is_required' => false,
                'guidance_text' => 'Upload any historical deeds in the chain of ownership.',
                'missing_guidance' => 'Check with the sub-registry office for historical deed records.',
                'accepted_formats' => json_encode(['pdf', 'jpg', 'jpeg', 'png']),
                'max_file_size_mb' => 10,
                'score_weight' => 5,
                'conditional_on_ownership' => null,
                'is_active' => true,
                'sort_order' => 11,
                'country_code' => 'BGD',
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);
    }

    public function down(): void
    {
        DB::table('document_types')->whereIn('slug', [
            'deed', 'tax-receipt', 'mutation-khatian', 'recorded-khatian',
            'court-decree', 'dcr', 'position-of-land', 'possession-of-land',
            'settlement-gazette', 'succession-certificate', 'via-deed',
        ])->delete();

        DB::table('ownership_types')->whereIn('slug', ['sole', 'joint'])->delete();

        DB::table('ownership_statuses')->whereIn('slug', [
            'purchase', 'gift', 'inheritance', 'court-decree',
            'lease', 'donation-trust', 'family',
        ])->delete();

        DB::table('property_types')->whereIn('slug', ['land', 'apartment', 'others'])->delete();
    }
};
