<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ServiceSeeder extends Seeder
{
    public function run(): void
    {
        // ── Categories ────────────────────────────────────────────
        $verificationId = DB::table('service_categories')->updateOrInsert(
            ['slug' => 'verification-assessment'],
            [
                'name' => 'Verification & Assessment',
                'description' => 'Property purchase/sale verification and due diligence',
                'icon' => 'shield-check',
                'is_active' => true,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ]
        );
        $verificationId = DB::table('service_categories')->where('slug', 'verification-assessment')->value('id');

        $registrationId = DB::table('service_categories')->updateOrInsert(
            ['slug' => 'registration-transfer'],
            [
                'name' => 'Registration & Transfer',
                'description' => 'Land registration, ownership transfer, and legal document services',
                'icon' => 'file-signature',
                'is_active' => true,
                'sort_order' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ]
        );
        $registrationId = DB::table('service_categories')->where('slug', 'registration-transfer')->value('id');

        $searchId = DB::table('service_categories')->updateOrInsert(
            ['slug' => 'document-search'],
            [
                'name' => 'Document Search & Records',
                'description' => 'Government record searching, document retrieval, and historical analysis',
                'icon' => 'search',
                'is_active' => true,
                'sort_order' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ]
        );
        $searchId = DB::table('service_categories')->where('slug', 'document-search')->value('id');

        $legalId = DB::table('service_categories')->updateOrInsert(
            ['slug' => 'legal-special'],
            [
                'name' => 'Legal & Special Cases',
                'description' => 'Inheritance, disputes, special property types, and legal proceedings',
                'icon' => 'scale',
                'is_active' => true,
                'sort_order' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ]
        );
        $legalId = DB::table('service_categories')->where('slug', 'legal-special')->value('id');

        // ── Services (matching Wisebox service catalog) ───────────
        $services = [
            // --- Verification & Assessment (services 2-5 from catalog) ---
            [
                'category_id' => $verificationId,
                'name' => 'Land Purchase Verification',
                'slug' => 'land-purchase-verification',
                'short_description' => 'Full due diligence for land purchase: document verification, field inspection, and ownership validation',
                'pricing_type' => 'paid',
                'price' => 10000.00,
                'currency' => 'BDT',
                'estimated_duration_minutes' => 60,
                'requires_meeting' => true,
                'is_featured' => true,
                'sort_order' => 1,
            ],
            [
                'category_id' => $verificationId,
                'name' => 'Apartment Purchase Verification',
                'slug' => 'apartment-purchase-verification',
                'short_description' => 'Comprehensive apartment due diligence including developer documents, RAJUK approval, and utility permits',
                'pricing_type' => 'paid',
                'price' => 10000.00,
                'currency' => 'BDT',
                'estimated_duration_minutes' => 60,
                'requires_meeting' => true,
                'is_featured' => true,
                'sort_order' => 2,
            ],
            [
                'category_id' => $verificationId,
                'name' => 'Land Sale Verification',
                'slug' => 'land-sale-verification',
                'short_description' => 'Pre-sale verification of land documents to ensure clean title transfer',
                'pricing_type' => 'paid',
                'price' => 10000.00,
                'currency' => 'BDT',
                'estimated_duration_minutes' => 60,
                'requires_meeting' => true,
                'is_featured' => true,
                'sort_order' => 3,
            ],
            [
                'category_id' => $verificationId,
                'name' => 'Apartment Sale Verification',
                'slug' => 'apartment-sale-verification',
                'short_description' => 'Pre-sale apartment document verification including developer agreements and building permits',
                'pricing_type' => 'paid',
                'price' => 10000.00,
                'currency' => 'BDT',
                'estimated_duration_minutes' => 60,
                'requires_meeting' => true,
                'is_featured' => true,
                'sort_order' => 4,
            ],

            // --- Registration & Transfer (service 6, 7, 24-27) ---
            [
                'category_id' => $registrationId,
                'name' => 'Land Registration (NRB/International)',
                'slug' => 'land-registration-nrb',
                'short_description' => 'Land registration assistance for Non-Resident Bangladeshis (NRB) including eligibility verification',
                'pricing_type' => 'paid',
                'price' => 15000.00,
                'currency' => 'BDT',
                'estimated_duration_minutes' => 90,
                'requires_meeting' => true,
                'is_featured' => true,
                'sort_order' => 5,
            ],
            [
                'category_id' => $registrationId,
                'name' => 'Land Registration (National)',
                'slug' => 'land-registration-national',
                'short_description' => 'Land registration assistance for Bangladeshi nationals including document preparation',
                'pricing_type' => 'paid',
                'price' => 12000.00,
                'currency' => 'BDT',
                'estimated_duration_minutes' => 90,
                'requires_meeting' => true,
                'is_featured' => false,
                'sort_order' => 6,
            ],
            [
                'category_id' => $registrationId,
                'name' => 'Land Ownership Papers',
                'slug' => 'land-ownership-papers',
                'short_description' => 'Assistance with Mutation, Land Development Tax, and government land records',
                'pricing_type' => 'paid',
                'price' => 8000.00,
                'currency' => 'BDT',
                'estimated_duration_minutes' => 60,
                'requires_meeting' => false,
                'is_featured' => false,
                'sort_order' => 7,
            ],
            [
                'category_id' => $registrationId,
                'name' => 'Power of Attorney',
                'slug' => 'power-of-attorney',
                'short_description' => 'Preparation and registration of Power of Attorney for property management',
                'pricing_type' => 'paid',
                'price' => 10000.00,
                'currency' => 'BDT',
                'estimated_duration_minutes' => 60,
                'requires_meeting' => true,
                'is_featured' => false,
                'sort_order' => 8,
            ],
            [
                'category_id' => $registrationId,
                'name' => 'Baynama Dolil',
                'slug' => 'baynama-dolil',
                'short_description' => 'Baynama (sale agreement) document preparation and registration',
                'pricing_type' => 'paid',
                'price' => 8000.00,
                'currency' => 'BDT',
                'estimated_duration_minutes' => 60,
                'requires_meeting' => true,
                'is_featured' => false,
                'sort_order' => 9,
            ],
            [
                'category_id' => $registrationId,
                'name' => 'Deed Document Lost',
                'slug' => 'deed-document-lost',
                'short_description' => 'Assistance with recovering or replacing lost deed documents',
                'pricing_type' => 'paid',
                'price' => 12000.00,
                'currency' => 'BDT',
                'estimated_duration_minutes' => 90,
                'requires_meeting' => true,
                'is_featured' => false,
                'sort_order' => 10,
            ],

            // --- Document Search & Records (services 10-14, 17, 18) ---
            [
                'category_id' => $searchId,
                'name' => 'Deed/Baiya/Pre-Deed Searching',
                'slug' => 'deed-searching',
                'short_description' => 'Search for deeds, baiya, and pre-deed documents in registration office records',
                'pricing_type' => 'paid',
                'price' => 5000.00,
                'currency' => 'BDT',
                'estimated_duration_minutes' => 45,
                'requires_meeting' => false,
                'is_featured' => false,
                'sort_order' => 11,
            ],
            [
                'category_id' => $searchId,
                'name' => 'Porcha Searching',
                'slug' => 'porcha-searching',
                'short_description' => 'Search for Porcha records in Settlement Office',
                'pricing_type' => 'paid',
                'price' => 5000.00,
                'currency' => 'BDT',
                'estimated_duration_minutes' => 45,
                'requires_meeting' => false,
                'is_featured' => false,
                'sort_order' => 12,
            ],
            [
                'category_id' => $searchId,
                'name' => 'Map & Khatian Searching',
                'slug' => 'map-khatian-searching',
                'short_description' => 'Search for maps and Khatian records in DC record room',
                'pricing_type' => 'paid',
                'price' => 5000.00,
                'currency' => 'BDT',
                'estimated_duration_minutes' => 45,
                'requires_meeting' => false,
                'is_featured' => false,
                'sort_order' => 13,
            ],
            [
                'category_id' => $searchId,
                'name' => 'Land Searching (Register II & IX)',
                'slug' => 'land-searching-register',
                'short_description' => 'Search land records in Union Land Office (Register II and Register IX)',
                'pricing_type' => 'paid',
                'price' => 5000.00,
                'currency' => 'BDT',
                'estimated_duration_minutes' => 45,
                'requires_meeting' => false,
                'is_featured' => false,
                'sort_order' => 14,
            ],
            [
                'category_id' => $searchId,
                'name' => 'Return Searching',
                'slug' => 'return-searching',
                'short_description' => 'Search for return records in Upazila Land Office',
                'pricing_type' => 'paid',
                'price' => 5000.00,
                'currency' => 'BDT',
                'estimated_duration_minutes' => 45,
                'requires_meeting' => false,
                'is_featured' => false,
                'sort_order' => 15,
            ],
            [
                'category_id' => $searchId,
                'name' => 'Pentagraph',
                'slug' => 'pentagraph',
                'short_description' => 'Pentagraph survey mapping and boundary verification',
                'pricing_type' => 'paid',
                'price' => 5000.00,
                'currency' => 'BDT',
                'estimated_duration_minutes' => 60,
                'requires_meeting' => false,
                'is_featured' => false,
                'sort_order' => 16,
            ],
            [
                'category_id' => $searchId,
                'name' => 'History Analysis of Khatian & Deed',
                'slug' => 'history-analysis',
                'short_description' => 'Complete historical chain analysis of Khatian records and deed ownership',
                'pricing_type' => 'paid',
                'price' => 8000.00,
                'currency' => 'BDT',
                'estimated_duration_minutes' => 90,
                'requires_meeting' => true,
                'is_featured' => false,
                'sort_order' => 17,
            ],

            // --- Legal & Special Cases (services 8, 9, 15, 16, 19-23) ---
            [
                'category_id' => $legalId,
                'name' => 'Inheritance Property',
                'slug' => 'inheritance-property',
                'short_description' => 'Inheritance property assessment and distribution based on religious law',
                'pricing_type' => 'paid',
                'price' => 15000.00,
                'currency' => 'BDT',
                'estimated_duration_minutes' => 90,
                'requires_meeting' => true,
                'is_featured' => false,
                'sort_order' => 18,
            ],
            [
                'category_id' => $legalId,
                'name' => 'Problem Identification & Solutions',
                'slug' => 'problem-identification',
                'short_description' => 'Identify land-related problems and provide actionable solutions',
                'pricing_type' => 'paid',
                'price' => 8000.00,
                'currency' => 'BDT',
                'estimated_duration_minutes' => 60,
                'requires_meeting' => true,
                'is_featured' => true,
                'sort_order' => 19,
            ],
            [
                'category_id' => $legalId,
                'name' => 'Misc Case (AC Land Office)',
                'slug' => 'misc-case',
                'short_description' => 'Filing and managing miscellaneous cases at the AC Land Office',
                'pricing_type' => 'paid',
                'price' => 10000.00,
                'currency' => 'BDT',
                'estimated_duration_minutes' => 60,
                'requires_meeting' => true,
                'is_featured' => false,
                'sort_order' => 20,
            ],
            [
                'category_id' => $legalId,
                'name' => 'Appeal Case',
                'slug' => 'appeal-case',
                'short_description' => 'Appeal cases to ADC Revenue, Additional Commissioner, or Land Appeal Board',
                'pricing_type' => 'paid',
                'price' => 15000.00,
                'currency' => 'BDT',
                'estimated_duration_minutes' => 90,
                'requires_meeting' => true,
                'is_featured' => false,
                'sort_order' => 21,
            ],
            [
                'category_id' => $legalId,
                'name' => 'Waqf Land Analysis',
                'slug' => 'waqf-land-analysis',
                'short_description' => 'Analysis and assessment of Waqf (religious endowment) land status',
                'pricing_type' => 'paid',
                'price' => 10000.00,
                'currency' => 'BDT',
                'estimated_duration_minutes' => 60,
                'requires_meeting' => true,
                'is_featured' => false,
                'sort_order' => 22,
            ],
            [
                'category_id' => $legalId,
                'name' => 'Vested Property',
                'slug' => 'vested-property',
                'short_description' => 'Assessment and resolution of vested (enemy) property status',
                'pricing_type' => 'paid',
                'price' => 15000.00,
                'currency' => 'BDT',
                'estimated_duration_minutes' => 90,
                'requires_meeting' => true,
                'is_featured' => false,
                'sort_order' => 23,
            ],
            [
                'category_id' => $legalId,
                'name' => 'Abandoned Property',
                'slug' => 'abandoned-property',
                'short_description' => 'Assessment of abandoned (porityokto) property status and recovery options',
                'pricing_type' => 'paid',
                'price' => 12000.00,
                'currency' => 'BDT',
                'estimated_duration_minutes' => 60,
                'requires_meeting' => true,
                'is_featured' => false,
                'sort_order' => 24,
            ],
            [
                'category_id' => $legalId,
                'name' => 'Mortgage Property',
                'slug' => 'mortgage-property',
                'short_description' => 'Mortgage property assessment, lien verification, and release assistance',
                'pricing_type' => 'paid',
                'price' => 10000.00,
                'currency' => 'BDT',
                'estimated_duration_minutes' => 60,
                'requires_meeting' => true,
                'is_featured' => false,
                'sort_order' => 25,
            ],
            [
                'category_id' => $legalId,
                'name' => 'Khash Land',
                'slug' => 'khash-land',
                'short_description' => 'Government Khash land status verification and settlement assistance',
                'pricing_type' => 'paid',
                'price' => 10000.00,
                'currency' => 'BDT',
                'estimated_duration_minutes' => 60,
                'requires_meeting' => true,
                'is_featured' => false,
                'sort_order' => 26,
            ],

            // General consultation (free initial meeting)
            [
                'category_id' => $verificationId,
                'name' => 'General Consultation',
                'slug' => 'general-consultation',
                'short_description' => 'Free initial consultation to discuss your property needs and recommended services',
                'pricing_type' => 'free',
                'price' => 0.00,
                'currency' => 'BDT',
                'estimated_duration_minutes' => 30,
                'requires_meeting' => true,
                'is_featured' => true,
                'sort_order' => 27,
            ],
        ];

        foreach ($services as $service) {
            DB::table('services')->updateOrInsert(
                ['slug' => $service['slug']],
                array_merge($service, [
                    'is_active' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ])
            );
        }

        // Deactivate old placeholder services (safe: preserves FK references)
        $validSlugs = array_column($services, 'slug');
        DB::table('services')->whereNotIn('slug', $validSlugs)->update(['is_active' => false]);
    }
}
